### ISSUE TITLE
19m param model

### ISSUE THREAD

**Issue by robflynnyh** [EleutherAI/pythia#60]
Where did the 19m model go to!

**Comment by haileyschoelkopf** [comment]
Hey! We recently renamed all models to take their embedding and unembedding layers into account, and to better reflect both the naming scheme used by OPT and GPT-2 as well as reflecting the model's size on GPU. 

In this case the 19m param model has become "pythia-70m", because at such a small scale the embedding layers are such a large portion of its parameters.

**Comment by robflynnyh** [comment]
Ah okay, that makes sense! thanks for clarifying
